name: Handle issues
on: [issues]
jobs:
  output-info:
    runs-on: ubuntu-latest
    steps:
      - name: Output info
        run: |
          echo "Issue: ${{ github.event.issue.title }}"
          echo "Issue event: ${{ toJson(github.event) }}"
